### ISSUE TITLE
Add more icons/symbols

### ISSUE THREAD

**Issue by z3to** [SensesProject/library#3]
- [ ] Symbol for external link (↗) (used in Toolkit)
- [ ] Symbol for open in modal (used in Toolkit)
- [ ] Social media

**Comment by fidelthomet** [comment]
- [ ] Small circle (•) `glyph-dot` for color color keys (used in GEMs)

**Comment by more-ginger** [comment]
added icons for: nuclear, biomass, world
fixed icon for electricity
